# cmake/shims/ECMConfig.cmake — vendor shim for find_package(ECM) NO_MODULE
set(PACKAGE_VERSION "6.8.0")
set(PACKAGE_VERSION_COMPATIBLE TRUE)
set(PACKAGE_VERSION_EXACT TRUE)
set(ECM_VERSION "6.8.0")
set(ECM_MODULE_DIR "${CMAKE_CURRENT_LIST_DIR}/../../third_party/extra-cmake-modules/modules" CACHE PATH "ECM modules")
set(ECM_FIND_MODULE_DIR "${CMAKE_CURRENT_LIST_DIR}/../../third_party/extra-cmake-modules/find-modules" CACHE PATH "ECM find-modules")
set(ECM_KDE_MODULE_DIR "${CMAKE_CURRENT_LIST_DIR}/../../third_party/extra-cmake-modules/kde-modules" CACHE PATH "ECM kde-modules")
# v1 教训: KSyntax 的 CMakeLists 用 set(CMAKE_MODULE_PATH ${ECM_MODULE_PATH}) 全量覆盖, 必须先建好 ECM_MODULE_PATH
set(ECM_MODULE_PATH "${ECM_MODULE_DIR}" "${ECM_FIND_MODULE_DIR}" "${ECM_KDE_MODULE_DIR}" CACHE PATH "ECM module search path (combined)")
list(APPEND CMAKE_MODULE_PATH ${ECM_MODULE_PATH})
include("${ECM_MODULE_DIR}/ECMUseFindModules.cmake" OPTIONAL RESULT_VARIABLE _ecm_use_loaded)
if(_ecm_use_loaded)
    message(STATUS "[ECMConfig shim] LOADED; PACKAGE_VERSION=${PACKAGE_VERSION}; ECM_VERSION=${ECM_VERSION}")
    message(STATUS "[ECMConfig shim] ECM_MODULE_PATH=${ECM_MODULE_PATH}")
endif()
